### ISSUE TITLE
Compatibility with `<Routes @rendermode="@(new InteractiveWebAssemblyRenderMode(prerender: false))" />`

### ISSUE THREAD

**Issue by NielsPilgaard** [ShaunCurtis/Blazr.RenderState#1]
Hi 👋 

I followed [this SO answer](https://stackoverflow.com/a/77659356/11794299) for setting up a loading screen in a Blazor Web App, using the WASM rendermode in dotnet 8, but I simply cannot get it to work.

Do you know if prerendering has to be enabled for your SO answer to work? :)

**Comment by ShaunCurtis** [comment]
Yes.  Pre-rendering is on by default, but you're disabling it.  The splash screen is what prerender gives you.  If you're still having issues, produce an MRE (see SO for MRE) and post a question on SO.  I'll see it.

**Comment by NielsPilgaard** [comment]
Damn, alright - Time for me to convert to SSR/BlazorServer, too many downsides in staying with WASM at this point. 
Thanks for your time 👍
